### ISSUE TITLE
tomcat部署好了，怎么添加文件到索引啊

### ISSUE THREAD

**Issue by alanljj** [iboxdb/ftserver#2]
input URL to index是怎么用？如果我要索引硬盘上的一个目录里的所有文件可以吗？

**Comment by iboxdb** [comment]
input URL == input  "https://github.com/"  ,or "http://www.iboxdb.com/" , or "http://....." ....

**Comment by iboxdb** [comment]
索引硬盘上的一个目录,  **Good Idea**

**Comment by alanljj** [comment]
我输入“https://github.com/”，错误为：

NotFound input https://github.com/

...input URL to index

如果能索引本地office文件pdf等，那就太棒了

**Comment by iboxdb** [comment]
@alanljj   http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136007.html
可能少了些安全组件,安装官方完整JDK试试。
